app:
  name: mvnwebapp

deployment:
  name: mavenwebappdeployment
  replicas: 1
  strategy: Recreate

image:
  repository: vinayomkar/mvnwebapp
  pullPolicy: IfNotPresent
  tag: "latest"

container:
  port: 80
  
service:
  type: ClusterIP
  port: 80
  targetPort: 8080

