apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ values.deployment.name }}
  namespace: {{ values.deployment.namespace }}
spec:
  revisionHistoryLimit: 10
  replicas: {{ values.deployment.replicas }}
  strategy:
    type: {{ values.deployment.strategy }}
  selector:
    matchLabels:
      app: {{ values.app.name }}
  template:
    metadata:
      labels:
        app: {{ values.app.name }}
    spec:
      containers:
        - name: {{ values.app.name }}
          image: "{{ .values.image.repository }}:{{ values.image.tag }}"
          pullPolicy: {{ values.image.pullPolicy }}
          ports:
            - containerPort: {{ values.container.port }}
